defmodule Browservm.Repo.Migrations.AddVms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vms, primary_key: false) do
      add :machine_name, :text, null: false, primary_key: true
      add :ami_id, :text, null: false
      add :ip_addr, :text
      add :status, :text, default: "requested"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:vms)
  end
end
